### ISSUE TITLE
How to add background scripts ?

### ISSUE THREAD

**Issue by yingyangcode** [pixochi/create-react-chrome-extension-ts#1]
How do i access the functionality of the background script ?

**Comment by pixochi** [comment]
Hi @yingyangcode , sorry for the late reply. I've just created a PR that adds support for background scripts. Could you give it a try? Please let me know if it solves your problem.

PR: https://github.com/pixochi/create-react-chrome-extension-ts/pull/2

**Comment by pixochi** [comment]
Support for background scripts was added in https://github.com/pixochi/create-react-chrome-extension-ts/pull/2.
